### ISSUE TITLE
Some PNG with Alpha Channel Failed to be Read Correctly

### ISSUE THREAD

**Issue by toyssamurai** [image-js/image-js#498]
For some reasons, some PNGs with an alpha channel would fail to be read correctly. Attached are two PNGs. 

**a.png** is the original file. If I load this image, channel count will be 3, and alpha will be 0. However, viewing the file in an image viewer will show that it does has an alpha channel. FYI, I tried loading the file using JIMP and JIMP reported that it does have an alpha channel.
![a](https://user-images.githubusercontent.com/14955849/75561206-9f7f7e80-5a14-11ea-833a-3eb921bce8fc.png)

<hr>

**b.png** is the same image, but I opened _a.png_ in PhotoShop and **saved** it as _b.png_. If I load this image, channel count will be 4 and alpha will be 0.
![b](https://user-images.githubusercontent.com/14955849/75561217-a27a6f00-5a14-11ea-84a1-e4173d980b70.png)

**Comment by targos** [comment]
So, I had a look at how that image is decoded, and it turns out that it is a palette image (which do not have an alpha channel by default) with an additional `tRNS` (transparency) chunk.
This is not yet supported by the decoder (https://github.com/image-js/fast-png).
It seems relatively easy to add support for it, I'm giving it a try.

**Comment by targos** [comment]
This should be fixed in version 0.21.9.
