### ISSUE TITLE
Write alpha channel into diff

### ISSUE THREAD

**Issue by santosh** [image-js/image-js#542]
I am using `subtractImage` to calculate the difference between two images. I am exporting it in png.

I tried playing with `channels` in options. Here's what I found:

With that option in place, values `0`, `1` and `2` puts the data in red, green and blue channel.  When I try with value 3, I get a blank image.

**Comment by targos** [comment]
What do you think about the following behavior change:

Instead of creating a new image for the result, do a copy of the "current" image and do the subtraction on that copy?
It would mean that by default, the result would have an alpha channel equal to the "current" image.
Also, if for example, you call `current.subtractImage(other, { channels: [0] })`, the result would have: red=original.red-other.red, green=original.green, blue=original.blue and alpha=original.alpha.

**Comment by santosh** [comment]
Below is the code I am using. The default resultant image is very close to what I want. I just want the alpha channel to be active too. 

```js
async function compare(image1, image2, diffimage) {
  const img1 = await Image.load(image1);
  const img2 = await Image.load(image2);

  const diff = img1.subtractImage(img2, {});

  await diff.save(diffimage);
}
```

From what you said, I think what you are saying is this:

```javascript
async function compare(image1, image2, diffimage) {
  const img1 = await Image.load(image1);
  const img2 = await Image.load(image2);

  img1.subtractImage(img2, { channels: [0, 1, 2, 3] });

  await img1.save(diffimage);
}
```

In the above case, I get the same image as img2 intact.

**Comment by targos** [comment]
The current behavior is that for channels that are not subtracted (by default the alpha channel), in the result that channel will be "empty" (0 for color channels or 255 for the alpha channel).
What I suggest to change in `image-js` (and we will do it if that corresponds to what you want), is to instead use the value of the first image. If we do the change, when you subtract two images that have an alpha channel, the resulting image would have exactly the same alpha channel as `img1`.
