### ISSUE TITLE
Feature Request:  Ability to handle 32bit rgb png files

### ISSUE THREAD

**Issue by delebash** [image-js/image-js#571]
Reason.  I am downloading 32bit images mapbox  for terrain heightmap data.  I need the 32bit rgb converted to 32bit gray scale and also into a 16bit grayscale for use in Unreal Engine as a heightmap.

Thanks!

**Comment by lpatiny** [comment]
Do you mean 32 bits per channel ? It seems to me that PNG is limited to 16 bits per channel:http://www.libpng.org/pub/png/book/chapter08.html#:~:text=RGB%20(truecolor)%20PNGs%2C%20like,and%2048%20bits%20per%20pixel.

**Comment by delebash** [comment]
I think I misunderstood. I am looking to converts 32 bit  Terrain-RGB PNG to a 32 bit RGB image depicting height as grey values from 0 to 255.   I am also looking to convert height encoded in RGB values to a 16 bit integer elevation.  I am new to image processing.  I am trying to create a 16 bit greyscale heightmap to import into Unreal Engine.  I also wanted a 32 bit rgb greyscale so that users can see what the 16 bit version will look like.  When a file is converted to 16 bit grey scale it can be hard to see the differences that is why I want the 32 bit version as well.   Can something like this be done using image-js?  Thank you for responding! Cheers

**Comment by lpatiny** [comment]
So in your PNG image you have 4 channels: R, G, B and A

Which channel contains what ?

Is it in fact a trick and in reality the values encoded is an elevation between 0 and 2^32-1 ?

So that you would need `R<<24 + G<<16 + B<<8 + A` to get the elevation ?

Or has this link suggest it would only be a value between 0 and 2^24-1 https://docs.mapbox.com/help/troubleshooting/access-elevation-data/

32 bit grayscale is not supported by PNG so we could only export 16 bits. But in this case you need to decide how you want to process the different channels.

**Comment by delebash** [comment]
I am actually downloading the files from mapbox.  Still new to this so I am not sure I understand but I will try.  So if I get each pixel separated into R,G,B and then use this formula height = -10000 + ((R * 256 * 256 + G * 256 + B) * 0.1)  I can get the height value of each pixel in meters?
