### ISSUE TITLE
[Question] How to process pen-filled multiple option assessments?

### ISSUE THREAD

**Issue by cesarpachon** [image-js/image-js#582]
Hello! I would like to implement the processing of pen-filled multiple option printed assessments, where all the answers are circles in a table and the user has to fill with a black pen the right answer in each row.
I wonder what would be the approach to this problem using image-js or if there is any other suggestion.
thanks!

**Comment by lpatiny** [comment]
Actually I'm using for my exams an existing tool: https://www.auto-multiple-choice.net/index.en and not image-js ...

There are a lot of features like generation of the exam with unique page identifier that would take a lot of time to reproduce. You need to write the exam in Latex but it was not that complex for me despite the fact I'm not familiar with Latex. 

Otherwise with image-js I would take care that there are black circle in the 4 corners of the page and that the place you need to check are 'squares'.

Then:

1. Get a grey scale scan of the assessments
2. Generate a mask based on one of the existing algorithm
3. Generate the region of interests
4. Use the various ROI properties to analyse the image: https://github.com/image-js/image-js/blob/5811f5b7e7677cdda1d8ac124a5c963812e5cd59/src/image/roi/Roi.js#L733-L756
5. Identify the 4 circles based on the sphericity and solidity
6. Rotate / move all the ROIs position based on the 4 circles
7. identify all the checkboxes based on sphericity and solidity (to know if they are checked or not)

Some explanation about the ROIs properties: 

https://docs.c6h6.org/docs/eln/other_analysis/images/includes/rois/README

You could test (using google chrome) this link: http://www.cheminfo.org/?viewURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2F187642421e225f8cfcd65a9243394a72%2Fview.json&loadversion=true&fillsearch=Image+analysis with your own image to explore masks and tune ROI parameters.
